name: test

on: [push]

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
        go-version: [1.16.x]
        golangcilint-version: [1.42.0]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v${{ matrix.golangcilint-version }}
      - name: Run CI test
        run: make ci-test
